# Permalinks
permalink:           pretty

# Setup
title:               smiling fire
tagline:             ''
description:         'This websites hosts my professional details along with some musings as a roboticist in training'
url:                 https://abhiagni.com/
baseurl:             ''
paginate:            5

# About/contact
# Credits to Mark Otto for lanyon
author:
  name:              Abhijeet Agnihotri
  url:               https://abhiagni.com/
  shorturl:          abhiagni.com/
  email:             abhijeet.agni.1993@gmail.com

# Custom vars
version:             1.0.0

github:
  repo: github.com/abhiagni11/abhiagni11.github.io

plugins:
  - jekyll-seo-tag
  - "jekyll-github-metadata"
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
