# Permalinks
permalink:           pretty

# Setup
title:               smilingfire
tagline:             ''
description:         ''
url:               http://abhiagni11.github.io
baseurl:             ''
paginate:            5

# About/contact
# Credits to Mark Otto for lanyon
author:
  name:              Abhijeet Agnihotri
  url:               http://abhiagni11.github.io
  shorturl:          abhiagni11.github.io
  email:             abhijeet.agni.1993@gmail.com

# Custom vars
version:             1.0.0

github:
  repo: github.com/abhiagni11/abhiagni11.github.io

plugins:
  - jekyll-seo-tag
  - "jekyll-github-metadata"
  - jekyll-redirect-from
  - jekyll-paginate
